# Generated by Django 5.0.14 on 2026-05-22 22:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('rol', models.CharField(blank=True, max_length=20)),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Bitácora',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('categoria', models.CharField(max_length=80)),
                ('valor', models.CharField(max_length=200)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha', 'categoria'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_pacientes', models.PositiveIntegerField(default=0)),
                ('generado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro diario',
            },
        ),
        migrations.CreateModel(
            name='TokenListaNegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('usuario', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('archivo', 'Archivo'), ('registros', 'Registros'), ('estadistica', 'Estadística'), ('juridico', 'Jurídico')], default='archivo', max_length=20)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('activo_sistema', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_apellido', models.CharField(max_length=80)),
                ('segundo_apellido', models.CharField(blank=True, max_length=80)),
                ('primer_nombre', models.CharField(max_length=80)),
                ('segundo_nombre', models.CharField(blank=True, max_length=80)),
                ('numero_expediente', models.CharField(editable=False, max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad_anios', models.PositiveSmallIntegerField(default=0)),
                ('edad_meses', models.PositiveSmallIntegerField(default=0)),
                ('edad_dias', models.PositiveSmallIntegerField(default=0)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado_civil', models.CharField(blank=True, max_length=30)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('nacionalidad', models.CharField(default='Guatemalteca', max_length=60)),
                ('dpi', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre_conyuge', models.CharField(blank=True, max_length=160)),
                ('nombre_padre', models.CharField(blank=True, max_length=160)),
                ('nombre_madre', models.CharField(blank=True, max_length=160)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('servicio', models.CharField(blank=True, max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('estado_paciente', models.CharField(default='Activo', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['primer_apellido', 'primer_nombre'],
                'indexes': [models.Index(fields=['primer_apellido', 'primer_nombre'], name='app_pacient_primer__e24425_idx'), models.Index(fields=['numero_expediente'], name='app_pacient_numero__3636b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteVAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(default='En trámite', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.CharField(blank=True, max_length=150)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vas', to='app.paciente')),
            ],
            options={
                'verbose_name': 'Expediente VAS',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('medico', models.CharField(blank=True, max_length=120)),
                ('motivo', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('reprogramada', models.BooleanField(default=False)),
                ('creado_por', models.CharField(blank=True, max_length=150)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='app.paciente')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('especialidad', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Programada', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='app.paciente')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDiarioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.registrodiario')),
            ],
        ),
    ]
