# Generated by Django 5.0.14 on 2026-05-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='servicio',
        ),
        migrations.AddField(
            model_name='paciente',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='paciente',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina general', 'Medicina general'), ('Medicina interna', 'Medicina interna'), ('Pediatría', 'Pediatría'), ('Ginecología y obstetricia', 'Ginecología y obstetricia'), ('Cirugía general', 'Cirugía general'), ('Traumatología', 'Traumatología'), ('Cardiología', 'Cardiología'), ('Neumología', 'Neumología'), ('Dermatología', 'Dermatología'), ('Oftalmología', 'Oftalmología'), ('Otorrinolaringología', 'Otorrinolaringología'), ('Psiquiatría', 'Psiquiatría'), ('Neurología', 'Neurología'), ('Urología', 'Urología'), ('Oncología', 'Oncología'), ('Endocrinología', 'Endocrinología'), ('Gastroenterología', 'Gastroenterología'), ('Nefrología', 'Nefrología'), ('Reumatología', 'Reumatología'), ('Medicina familiar', 'Medicina familiar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Viudo(a)', 'Viudo(a)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_paciente',
            field=models.CharField(choices=[('Control', 'Control'), ('Primera vez', 'Primera vez')], default='Primera vez', max_length=20),
        ),
    ]
