# Generated by Django 5.0.14 on 2026-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuario_clave_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('Medicina Interna (MI)', 'Medicina Interna (MI)'), ('Violencia y Abuso Sexual (VAS)', 'Violencia y Abuso Sexual (VAS)'), ('Medicina General (MG)', 'Medicina General (MG)'), ('Traumatología Mujeres (TM)', 'Traumatología Mujeres (TM)'), ('Traumatología Hombres (TH)', 'Traumatología Hombres (TH)'), ('Pediatría (P)', 'Pediatría (P)'), ('Psicología (PS)', 'Psicología (PS)'), ('Psiquiatría (PQ)', 'Psiquiatría (PQ)'), ('Traumatología Pediátrica (TP)', 'Traumatología Pediátrica (TP)'), ('Nutrición (N)', 'Nutrición (N)'), ('Alto Riesgo (ARO)', 'Alto Riesgo (ARO)'), ('Ginecología (GINE)', 'Ginecología (GINE)'), ('Cirugía Mujeres (CM)', 'Cirugía Mujeres (CM)'), ('Cirugía Hombres (CH)', 'Cirugía Hombres (CH)'), ('Odontología (ODO)', 'Odontología (ODO)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina Interna (MI)', 'Medicina Interna (MI)'), ('Violencia y Abuso Sexual (VAS)', 'Violencia y Abuso Sexual (VAS)'), ('Medicina General (MG)', 'Medicina General (MG)'), ('Traumatología Mujeres (TM)', 'Traumatología Mujeres (TM)'), ('Traumatología Hombres (TH)', 'Traumatología Hombres (TH)'), ('Pediatría (P)', 'Pediatría (P)'), ('Psicología (PS)', 'Psicología (PS)'), ('Psiquiatría (PQ)', 'Psiquiatría (PQ)'), ('Traumatología Pediátrica (TP)', 'Traumatología Pediátrica (TP)'), ('Nutrición (N)', 'Nutrición (N)'), ('Alto Riesgo (ARO)', 'Alto Riesgo (ARO)'), ('Ginecología (GINE)', 'Ginecología (GINE)'), ('Cirugía Mujeres (CM)', 'Cirugía Mujeres (CM)'), ('Cirugía Hombres (CH)', 'Cirugía Hombres (CH)'), ('Odontología (ODO)', 'Odontología (ODO)')], max_length=100),
        ),
    ]
