# Generated by Django 6.0.5 on 2026-08-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_especialidades_preop_nefro_tarde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(choices=[('Medicina Interna (MI)', 'Medicina Interna (MI)'), ('Violencia y Abuso Sexual (VAS)', 'Violencia y Abuso Sexual (VAS)'), ('Medicina General (MG)', 'Medicina General (MG)'), ('Medicina General Tarde (MGT)', 'Medicina General Tarde (MGT)'), ('Traumatología Mujeres (TM)', 'Traumatología Mujeres (TM)'), ('Traumatología Hombres (TH)', 'Traumatología Hombres (TH)'), ('Pediatría (P)', 'Pediatría (P)'), ('Psicología (PS)', 'Psicología (PS)'), ('Psicología Tarde (PST)', 'Psicología Tarde (PST)'), ('Psiquiatría (PQ)', 'Psiquiatría (PQ)'), ('Traumatología Pediátrica (TP)', 'Traumatología Pediátrica (TP)'), ('Nutrición (N)', 'Nutrición (N)'), ('Alto Riesgo (ARO)', 'Alto Riesgo (ARO)'), ('Ginecología (GINE)', 'Ginecología (GINE)'), ('Cirugía Mujeres (CM)', 'Cirugía Mujeres (CM)'), ('Cirugía Hombres (CH)', 'Cirugía Hombres (CH)'), ('Odontología (ODO)', 'Odontología (ODO)'), ('Preoperatorio (PREOP)', 'Preoperatorio (PREOP)'), ('Nefrología (NEFRO)', 'Nefrología (NEFRO)'), ('Electrocardiograma (EKG)', 'Electrocardiograma (EKG)'), ('Videocirugía (VC)', 'Videocirugía (VC)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina Interna (MI)', 'Medicina Interna (MI)'), ('Violencia y Abuso Sexual (VAS)', 'Violencia y Abuso Sexual (VAS)'), ('Medicina General (MG)', 'Medicina General (MG)'), ('Medicina General Tarde (MGT)', 'Medicina General Tarde (MGT)'), ('Traumatología Mujeres (TM)', 'Traumatología Mujeres (TM)'), ('Traumatología Hombres (TH)', 'Traumatología Hombres (TH)'), ('Pediatría (P)', 'Pediatría (P)'), ('Psicología (PS)', 'Psicología (PS)'), ('Psicología Tarde (PST)', 'Psicología Tarde (PST)'), ('Psiquiatría (PQ)', 'Psiquiatría (PQ)'), ('Traumatología Pediátrica (TP)', 'Traumatología Pediátrica (TP)'), ('Nutrición (N)', 'Nutrición (N)'), ('Alto Riesgo (ARO)', 'Alto Riesgo (ARO)'), ('Ginecología (GINE)', 'Ginecología (GINE)'), ('Cirugía Mujeres (CM)', 'Cirugía Mujeres (CM)'), ('Cirugía Hombres (CH)', 'Cirugía Hombres (CH)'), ('Odontología (ODO)', 'Odontología (ODO)'), ('Preoperatorio (PREOP)', 'Preoperatorio (PREOP)'), ('Nefrología (NEFRO)', 'Nefrología (NEFRO)'), ('Electrocardiograma (EKG)', 'Electrocardiograma (EKG)'), ('Videocirugía (VC)', 'Videocirugía (VC)')], max_length=100),
        ),
    ]
